In [1]:
import tensorflow as tf

In [20]:
input = tf.Variable(tf.ones([1,3,3,5]))
filter = tf.Variable(tf.ones([1,1,5,1]))
op = tf.nn.conv2d(input, filter, strides=[1, 5, 5, 1], padding='SAME')

In [22]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    res = (sess.run(op))
    print(sess.run(input))
    print(sess.run(filter))
    print(sess.run(op))

[[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]
[[[[1.]
   [1.]
   [1.]
   [1.]
   [1.]]]]
[[[[5.]]]]


In [4]:
input


<tf.Variable 'Variable:0' shape=(1, 3, 3, 5) dtype=float32_ref>

In [5]:
print(op)

Tensor("Conv2D:0", shape=(1, 3, 3, 1), dtype=float32)
